### ISSUE TITLE
Add support hover icon to all brochure "Web" projects

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/ChumsWeb#18]
Add a floating support button in the bottom right corner of all the brochure sites (ChumsWeb, StreamingLiveWeb, ChurchAppsWeb, and I guess the public pages of LessonsApp).  Just open the support modal from AppBase when clicked.

**Comment by PhotoPaul** [comment]
I'm closing this since all 4 of these brochure sites have a working support button:
- https://chums.org/
- https://streaminglive.church/
- https://b1.church/
- https://churchapps.org/
